server:
  port: 8080

spring:
  application:
    name: api-gateway
    jwt-secret: aGVsbG9teWRhcmxpbmcxMjk3NjUzMDk4MTUyNzc4OW9wdHk=
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/** # Path predicate for URI path matching
          filters:
            - AuthenticationFilter

logging:
  level:
    root: debug

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
