spring:
  application:
    name: user-service
    jwt-secret: aGVsbG9teWRhcmxpbmcxMjk3NjUzMDk4MTUyNzc4OW9wdHk=
    jwtExpirationMs: 600000
  datasource:
    url: jdbc:mysql://localhost:3306/ewallet_users
    username: root
    password: HelloMoto123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

user:
  redis:
    key:
      expiry: 14400

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: debug